services:
  postgres:
    image: postgres:16

    container_name: retail-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  minio:
    image: minio/minio:latest

    container_name: retail-minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    restart: unless-stopped

  spark:
    image: apache/spark:3.5.1

    container_name: retail-spark

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    ports:
      - "8080:8080"
      - "7077:7077"

    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: